//! The registry wire schema and every rule that can be decided without
//! touching the network or the disk: parsing, serial monotonicity, and the
//! fail-closed revocation rules.
//!
//! This file has no I/O on purpose. The monotonicity and fail-closed rules
//! are the part of the client most likely to be wrong and the part a network
//! or filesystem dependency would make untestable, so they live where a unit
//! test can reach all of them directly. Fetching is [`super::fetch`],
//! persistence is [`super::cache`] — and `cache` runs every document back
//! through the functions here on the way OUT of the disk as well as in, so
//! these rules hold on both sides of it.

use serde::{Deserialize, Serialize};

/// The only `schema_version` this client understands. A bump is a breaking
/// change the design expects never to make; if one ever happens the old URL
/// keeps serving a frozen v1 file, so refusing an unknown version leaves a
/// deployed client with a working (if frozen) view rather than a broken one.
pub const SUPPORTED_SCHEMA_VERSION: u32 = 1;

/// The entry `type` this client installs. Unknown types are skipped rather
/// than rejected — that is what makes the schema's "supports themes from day
/// one" claim true, and a v1 client must not break when the first
/// `"type": "theme"` entry appears.
const ENTRY_TYPE_PLUGIN: &str = "plugin";

/// A ready-made site the desktop app offers as a place to start. It rides in
/// the same signed index as plugins, so it is covered by the same signature,
/// serial and revocation rules.
const ENTRY_TYPE_STARTER: &str = "starter";

/// One installable plugin, exactly as the index publishes it.
///
/// Every field here is generated by registry CI from the manifest *inside*
/// the published zip, so the entry cannot describe something other than what
/// it points at. Post-install the installed manifest is authoritative.
///
/// Unknown fields are ignored (serde's default, kept deliberately): the
/// registry adds fields additively and an older moss must keep working.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct IndexEntry {
    /// `plugin` today; `theme` in phase 2. Entries whose type this client
    /// does not know are skipped by [`RegistryIndex::plugins`].
    #[serde(rename = "type")]
    pub entry_type: String,
    pub id: String,
    pub display_name: String,
    pub version: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub author: Option<String>,
    #[serde(default)]
    pub repository: Option<String>,
    #[serde(default)]
    pub capabilities: Vec<String>,
    pub download_url: String,
    /// The artifact hash pinned at review time. This is the whole integrity
    /// story: what was reviewed is what installs, wherever it is hosted.
    pub sha256: String,
    #[serde(default)]
    pub size_bytes: u64,
    /// The oldest moss that may run this version. Absent means no floor.
    #[serde(default)]
    pub min_moss_version: Option<String>,
    /// Declared host capabilities beyond the default table. Each entry names
    /// one executable as `execute_binary:<basename>`; the bare `execute_binary`
    /// is the deprecated blanket that grants every one of them. Free-form on
    /// purpose — the grant is decided where a binary is actually run, not here.
    #[serde(default)]
    pub requires: Option<Vec<String>>,
    #[serde(default)]
    pub icon_url: Option<String>,
    /// The publisher does not consider this version ready to be offered by
    /// default. Presentation only — it decides who is SHOWN the row, never
    /// who may install it.
    #[serde(default)]
    pub preview: bool,
    /// The plugin's runtime is a machine-wide companion stack downloaded on
    /// first install (OnionPress).
    #[serde(default)]
    pub requires_stack: bool,
    /// Every field this struct does not name. Kept only so
    /// [`RegistryIndex::starters`] can read the fields that belong to a
    /// starter without every entry type's fields living on this one struct.
    #[serde(flatten, default)]
    extra: serde_json::Map<String, serde_json::Value>,
}

/// One stop on a starter's guided tour: a label and the page it opens.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TourStop {
    pub label: String,
    pub path: String,
}

/// One starter site, exactly as the index publishes it.
///
/// Unknown fields are ignored, as for [`IndexEntry`]. The archive hashes pin
/// what was reviewed; fetching and checking them is the caller's job.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct StarterEntry {
    pub id: String,
    pub version: String,
    pub display_name: String,
    #[serde(default)]
    pub description: String,
    /// Where the sample content came from.
    #[serde(default)]
    pub credit: String,
    /// Display order, ascending.
    #[serde(default)]
    pub order: u32,
    /// The oldest moss that may open this starter. Absent means no floor.
    #[serde(default)]
    pub min_moss_version: Option<String>,
    #[serde(default)]
    pub tour: Vec<TourStop>,
    pub download_url: String,
    pub sha256: String,
    #[serde(default)]
    pub size_bytes: u64,
    /// A prebuilt copy of the site for previewing without building it.
    #[serde(default)]
    pub preview_url: Option<String>,
    #[serde(default)]
    pub preview_sha256: Option<String>,
    #[serde(default)]
    pub preview_size_bytes: u64,
    /// A full site made with this starter, wherever its author chose to put
    /// it. Optional; the index does not check what it points at.
    #[serde(default)]
    pub demo_url: Option<String>,
}

/// The published catalog. Exactly one entry per id — the latest version — so
/// "which version replaced a revoked one" is always "the current entry for
/// that id, if not itself revoked".
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RegistryIndex {
    pub schema_version: u32,
    /// Monotonic. Clients persist the highest seen and reject anything lower
    /// — replay/downgrade protection.
    pub serial: u64,
    /// NOT `#[serde(default)]`, and that is load-bearing. With a default, an
    /// `index.json` served at the `revoked.json` URL — a Pages redirect, a
    /// wrong path in the publish workflow — parses cleanly as an empty kill
    /// list at the index's much higher serial, silently un-revoking
    /// everything and locking the real list out until a maintainer bumps
    /// past it. Requiring each document's own discriminating key is what
    /// makes the wrong one land as `Unparseable`, which fails closed.
    pub entries: Vec<IndexEntry>,
}

impl RegistryIndex {
    /// The entries this client can act on: known type only, a usable id, and
    /// at most one per id (first wins, matching the index's own
    /// one-entry-per-id invariant — a duplicate would be a registry bug, and
    /// silently preferring the first is the behaviour that cannot surprise).
    pub fn plugins(&self) -> Vec<&IndexEntry> {
        self.entries_of(ENTRY_TYPE_PLUGIN)
    }

    /// The starter sites, under the same id rules as [`Self::plugins`]. A
    /// starter row that does not read as a [`StarterEntry`] is dropped, like
    /// one with an unusable id, so it cannot take the plugin catalog with it.
    pub fn starters(&self) -> Vec<StarterEntry> {
        self.entries_of(ENTRY_TYPE_STARTER)
            .into_iter()
            .filter_map(|e| serde_json::from_value(serde_json::to_value(e).ok()?).ok())
            .collect()
    }

    fn entries_of(&self, entry_type: &str) -> Vec<&IndexEntry> {
        let mut seen: Vec<&str> = Vec::new();
        let mut out = Vec::new();
        for entry in &self.entries {
            if entry.entry_type != entry_type {
                continue;
            }
            if !crate::plugins::install::is_usable_id(&entry.id) {
                continue;
            }
            if seen.contains(&entry.id.as_str()) {
                continue;
            }
            seen.push(&entry.id);
            out.push(entry);
        }
        out
    }

    pub fn find(&self, id: &str) -> Option<&IndexEntry> {
        self.plugins().into_iter().find(|e| e.id == id)
    }
}

/// One revoked plugin, by id and version set.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Revocation {
    pub id: String,
    /// An explicit version list, or the single element `"*"` meaning every
    /// version of this id.
    pub versions: Vec<String>,
    /// Shown to the user on the badged row. The whole point of revocation
    /// reaching a human rather than only a code path.
    #[serde(default)]
    pub reason: String,
    #[serde(default)]
    pub advisory_url: Option<String>,
}

impl Revocation {
    /// Whether this revocation covers `version`.
    pub fn covers(&self, version: &str) -> bool {
        self.versions.iter().any(|v| v == "*" || v == version)
    }
}

/// The kill list.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RevokedList {
    pub schema_version: u32,
    pub serial: u64,
    /// Required, not defaulted — see [`RegistryIndex::entries`] for why the
    /// two documents must not be parseable as one another.
    pub revocations: Vec<Revocation>,
}

impl RevokedList {
    /// The revocation covering this exact id+version, if any.
    pub fn find(&self, id: &str, version: &str) -> Option<&Revocation> {
        self.revocations
            .iter()
            .find(|r| r.id == id && r.covers(version))
    }
}

/// Why a freshly fetched document was refused in favour of the cached one.
///
/// Every variant means the same thing to the caller — keep enforcing the
/// last-known-good cache — and they are distinguished only so the log says
/// which rule fired.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RejectReason {
    /// The bytes did not parse as the document they claim to be.
    Unparseable(String),
    /// `schema_version` is not one this client understands.
    UnknownSchemaVersion(u32),
    /// `serial` went backwards — a replay of an older file.
    SerialWentBackwards { seen: u64, offered: u64 },
    /// The revocation set shrank without the serial advancing. A shrink is
    /// legitimate only as a deliberate, serial-bumped edit; without the bump
    /// it is indistinguishable from a rollback, so it is refused.
    RevocationSetShrank { seen: usize, offered: usize },
}

impl std::fmt::Display for RejectReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RejectReason::Unparseable(e) => write!(f, "could not be parsed ({e})"),
            RejectReason::UnknownSchemaVersion(v) => {
                write!(f, "declares unsupported schema_version {v}")
            }
            RejectReason::SerialWentBackwards { seen, offered } => {
                write!(f, "serial went backwards ({offered} < highest seen {seen})")
            }
            RejectReason::RevocationSetShrank { seen, offered } => write!(
                f,
                "revocation set shrank from {seen} to {offered} without a serial increase"
            ),
        }
    }
}

/// Parse and accept a freshly fetched `index.json`.
///
/// `highest_seen_serial` is the highest serial this client has ever accepted
/// for the index (0 on a first run). Anything at or below it is a replay.
///
/// An equal serial is accepted, not refused: the app refreshes on both launch
/// and catalog open, so re-fetching the same unchanged file is the ordinary
/// case, not an attack. Only a serial that went *backwards* is a replay.
pub fn accept_index(raw: &str, highest_seen_serial: u64) -> Result<RegistryIndex, RejectReason> {
    let index: RegistryIndex =
        serde_json::from_str(raw).map_err(|e| RejectReason::Unparseable(e.to_string()))?;
    if index.schema_version != SUPPORTED_SCHEMA_VERSION {
        return Err(RejectReason::UnknownSchemaVersion(index.schema_version));
    }
    if index.serial < highest_seen_serial {
        return Err(RejectReason::SerialWentBackwards {
            seen: highest_seen_serial,
            offered: index.serial,
        });
    }
    Ok(index)
}

/// Parse and accept a freshly fetched `revoked.json`.
///
/// Fails closed in every direction. "Can't parse" never means "nothing
/// revoked" — the caller keeps enforcing the cached list, whose enforcement
/// therefore survives offline periods and hostile serving alike. That is the
/// asymmetry the design insists on: readiness fails open, revocation fails
/// closed, and the two are never folded together.
///
/// `cached_count` is how many revocations the last-known-good list held; it
/// exists so a set that shrank without a serial increase is refused.
pub fn accept_revoked(
    raw: &str,
    highest_seen_serial: u64,
    cached_count: usize,
) -> Result<RevokedList, RejectReason> {
    let list: RevokedList =
        serde_json::from_str(raw).map_err(|e| RejectReason::Unparseable(e.to_string()))?;
    if list.schema_version != SUPPORTED_SCHEMA_VERSION {
        return Err(RejectReason::UnknownSchemaVersion(list.schema_version));
    }
    if list.serial < highest_seen_serial {
        return Err(RejectReason::SerialWentBackwards {
            seen: highest_seen_serial,
            offered: list.serial,
        });
    }
    // A shrink at an UNCHANGED serial is the rollback shape: `revoked.json`
    // is hand-edited and CI rejects an edit that does not raise the serial,
    // so a smaller set at the same serial cannot have come from a maintainer.
    if list.serial == highest_seen_serial && list.revocations.len() < cached_count {
        return Err(RejectReason::RevocationSetShrank {
            seen: cached_count,
            offered: list.revocations.len(),
        });
    }
    Ok(list)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A minimal valid index. Tests mutate the pieces they are about.
    fn index_json(serial: u64, entries: &str) -> String {
        format!(r#"{{"schema_version":1,"serial":{serial},"entries":[{entries}]}}"#)
    }

    fn entry(id: &str, entry_type: &str) -> String {
        format!(
            r#"{{"type":"{entry_type}","id":"{id}","display_name":"{id}","version":"1.0.0",
                 "download_url":"https://example.invalid/{id}.zip","sha256":"aa"}}"#
        )
    }

    fn revoked_json(serial: u64, revocations: &str) -> String {
        format!(r#"{{"schema_version":1,"serial":{serial},"revocations":[{revocations}]}}"#)
    }

    #[test]
    fn accepts_a_first_index_and_reads_its_entries() {
        let raw = index_json(28, &entry("github", "plugin"));
        let index = accept_index(&raw, 0).expect("a first index must be accepted");
        assert_eq!(index.serial, 28);
        assert_eq!(index.plugins().len(), 1);
        assert_eq!(index.find("github").unwrap().version, "1.0.0");
    }

    #[test]
    fn drops_entries_whose_id_could_not_be_a_directory_name() {
        // The id names a directory that gets created, unpacked into and
        // recursively deleted, so an index served at the pinned URL must not
        // be able to pick that path. Dropping the entry — rather than refusing
        // the whole document — keeps one malformed row from taking the catalog
        // down with it.
        let hostile = format!(
            "{},{}",
            entry("../../../etc", "plugin"),
            entry("github", "plugin")
        );
        let index = accept_index(&index_json(1, &hostile), 0).expect("the document itself is fine");
        assert_eq!(
            index.plugins().iter().map(|e| e.id.as_str()).collect::<Vec<_>>(),
            vec!["github"],
            "an id that escapes its directory is not an id"
        );
    }

    #[test]
    fn tolerates_unknown_fields_so_the_registry_can_add_them() {
        // The registry adds fields additively; an older moss must keep working.
        let raw = r#"{"schema_version":1,"serial":1,"unheard_of":true,"entries":[
            {"type":"plugin","id":"x","display_name":"X","version":"1.0.0",
             "download_url":"https://example.invalid/x.zip","sha256":"aa","brand_new":42}]}"#;
        let index = accept_index(raw, 0).expect("unknown fields must be ignored");
        assert_eq!(index.plugins().len(), 1);
    }

    #[test]
    fn skips_unknown_entry_types_rather_than_failing() {
        // This is what makes "the schema supports themes from day one" true:
        // a v1 client must not break when the first theme entry appears.
        let both = format!("{},{}", entry("dusk", "theme"), entry("github", "plugin"));
        let index = accept_index(&index_json(2, &both), 0).unwrap();
        let ids: Vec<&str> = index.plugins().iter().map(|e| e.id.as_str()).collect();
        assert_eq!(ids, vec!["github"], "a theme entry must be skipped, not fatal");
    }

    fn starter(id: &str, extra: &str) -> String {
        format!(
            r#"{{"type":"starter","id":"{id}","version":"1.0.0","display_name":"Essays",
                 "description":"A writer's own site","credit":"Filled with public-domain essays",
                 "language":"en","order":10,"min_moss_version":"0.15.4",
                 "tour":[{{"label":"Home","path":"/"}}],
                 "download_url":"https://example.invalid/{id}.zip","sha256":"{sha}","size_bytes":7,
                 "preview_url":"https://example.invalid/{id}-preview.zip",
                 "preview_sha256":"{sha}","preview_size_bytes":9,"preview_moss_version":"0.15.4"{extra}}}"#,
            sha = "ab".repeat(32)
        )
    }

    #[test]
    fn starters_are_read_and_plugins_stay_apart() {
        let both = format!("{},{}", starter("essays", ""), entry("github", "plugin"));
        let index = accept_index(&index_json(3, &both), 0).unwrap();
        let starters = index.starters();
        assert_eq!(starters.len(), 1);
        let s = &starters[0];
        assert_eq!((s.id.as_str(), s.order), ("essays", 10));
        assert_eq!(s.min_moss_version.as_deref(), Some("0.15.4"));
        assert_eq!(s.tour, vec![TourStop { label: "Home".into(), path: "/".into() }]);
        assert_eq!(s.preview_size_bytes, 9);
        assert_eq!(s.sha256, "ab".repeat(32));
        let ids: Vec<&str> = index.plugins().iter().map(|e| e.id.as_str()).collect();
        assert_eq!(ids, vec!["github"], "a starter is not a plugin");
        assert!(index.find("essays").is_none());
    }

    #[test]
    fn an_index_with_only_plugins_has_no_starters() {
        let index = accept_index(&index_json(1, &entry("github", "plugin")), 0).unwrap();
        assert!(index.starters().is_empty());
    }

    #[test]
    fn a_starter_with_an_unusable_id_is_dropped_and_the_rest_survive() {
        let both = format!("{},{}", starter("../../etc", ""), starter("essays", ""));
        let index = accept_index(&index_json(1, &both), 0).unwrap();
        let ids: Vec<String> = index.starters().into_iter().map(|s| s.id).collect();
        assert_eq!(ids, vec!["essays"]);
    }

    #[test]
    fn a_malformed_starter_is_dropped_without_failing_the_index() {
        let bad = r#"{"type":"starter","id":"broken","version":"1.0.0","display_name":"B",
            "download_url":"https://example.invalid/b.zip","sha256":"aa","tour":"not a list"}"#;
        let both = format!("{bad},{}", starter("essays", ""));
        let index = accept_index(&index_json(1, &both), 0).expect("one bad row is not fatal");
        let ids: Vec<String> = index.starters().into_iter().map(|s| s.id).collect();
        assert_eq!(ids, vec!["essays"]);
    }

    #[test]
    fn a_starter_carries_its_demo_url_when_it_has_one() {
        let with = format!("{},{}", starter("essays", r#","demo_url":"https://essays.example.org/""#), starter("plain", ""));
        let index = accept_index(&index_json(1, &with), 0).unwrap();
        let demos: Vec<Option<String>> = index.starters().into_iter().map(|s| s.demo_url).collect();
        assert_eq!(demos, vec![Some("https://essays.example.org/".to_string()), None]);
    }

    #[test]
    fn a_starter_ignores_fields_it_does_not_know() {
        let index = accept_index(&index_json(1, &starter("essays", r#","brand_new":42"#)), 0).unwrap();
        assert_eq!(index.starters().len(), 1);
    }

    #[test]
    fn refuses_an_unknown_schema_version() {
        let raw = r#"{"schema_version":2,"serial":99,"entries":[]}"#;
        assert!(matches!(
            accept_index(raw, 0),
            Err(RejectReason::UnknownSchemaVersion(2))
        ));
    }

    #[test]
    fn refuses_an_index_whose_serial_went_backwards() {
        // Replay of an archived index. The cached one stays in force.
        let raw = index_json(27, "");
        assert!(matches!(
            accept_index(&raw, 28),
            Err(RejectReason::SerialWentBackwards { seen: 28, offered: 27 })
        ));
    }

    #[test]
    fn accepts_an_unchanged_serial_because_refresh_runs_twice_a_session() {
        // Launch and catalog-open both refresh; re-fetching the same file is
        // the ordinary case, not an attack.
        assert!(accept_index(&index_json(28, ""), 28).is_ok());
    }

    #[test]
    fn refuses_unparseable_bytes() {
        assert!(matches!(
            accept_index("<!doctype html>", 0),
            Err(RejectReason::Unparseable(_))
        ));
    }

    #[test]
    fn keeps_the_first_entry_when_an_id_appears_twice() {
        let dup = format!("{},{}", entry("github", "plugin"), entry("github", "plugin"));
        let index = accept_index(&index_json(1, &dup), 0).unwrap();
        assert_eq!(index.plugins().len(), 1, "one entry per id is the invariant");
    }

    // --- the kill list: every rule here fails CLOSED ---

    #[test]
    fn revocation_matches_an_explicit_version_and_not_its_neighbours() {
        let raw = revoked_json(
            2,
            r#"{"id":"bad","versions":["1.1.0","1.1.1"],"reason":"exfiltrated the vault"}"#,
        );
        let list = accept_revoked(&raw, 0, 0).unwrap();
        assert_eq!(list.find("bad", "1.1.0").unwrap().reason, "exfiltrated the vault");
        assert!(list.find("bad", "1.1.1").is_some());
        assert!(list.find("bad", "1.2.0").is_none(), "the fixed version must not be revoked");
        assert!(list.find("other", "1.1.0").is_none());
    }

    #[test]
    fn a_star_revokes_every_version_of_that_id() {
        let raw = revoked_json(2, r#"{"id":"bad","versions":["*"],"reason":"malware"}"#);
        let list = accept_revoked(&raw, 0, 0).unwrap();
        assert!(list.find("bad", "0.0.1").is_some());
        assert!(list.find("bad", "99.0.0").is_some());
        assert!(list.find("good", "1.0.0").is_none());
    }

    #[test]
    fn unparseable_kill_list_is_refused_so_it_can_never_mean_nothing_revoked() {
        // The single most important test in this file. "Can't parse" must not
        // read as "nothing revoked" — the caller keeps enforcing the cache.
        assert!(matches!(
            accept_revoked("}{ not json", 3, 1),
            Err(RejectReason::Unparseable(_))
        ));
    }

    #[test]
    fn refuses_a_kill_list_whose_serial_went_backwards() {
        let raw = revoked_json(1, "");
        assert!(matches!(
            accept_revoked(&raw, 7, 2),
            Err(RejectReason::SerialWentBackwards { seen: 7, offered: 1 })
        ));
    }

    #[test]
    fn refuses_a_kill_list_that_shrank_without_the_serial_moving() {
        // The rollback shape: registry CI rejects a revoked.json edit that
        // does not raise the serial, so a smaller set at the same serial
        // cannot have come from a maintainer.
        let raw = revoked_json(7, "");
        assert!(matches!(
            accept_revoked(&raw, 7, 2),
            Err(RejectReason::RevocationSetShrank { seen: 2, offered: 0 })
        ));
    }

    #[test]
    fn allows_a_shrink_that_raised_the_serial() {
        // A maintainer genuinely un-revoking something is a serial-bumped edit.
        let raw = revoked_json(8, "");
        assert!(accept_revoked(&raw, 7, 2).is_ok());
    }

    #[test]
    fn allows_the_same_kill_list_to_arrive_again_unchanged() {
        let raw = revoked_json(7, r#"{"id":"bad","versions":["*"],"reason":"malware"}"#);
        assert!(accept_revoked(&raw, 7, 1).is_ok());
    }

    #[test]
    fn refuses_a_kill_list_with_an_unknown_schema_version() {
        let raw = r#"{"schema_version":9,"serial":100,"revocations":[]}"#;
        assert!(matches!(
            accept_revoked(raw, 1, 0),
            Err(RejectReason::UnknownSchemaVersion(9))
        ));
    }

    #[test]
    fn parses_the_live_index_shape_verbatim() {
        // Captured from https://symbiosis-lab.org/moss-registry/index.json.
        // Pins the real-world variation the type must absorb: min_moss_version
        // and requires each absent on some entries, requires_stack present on
        // one, repository absent on all.
        let raw = include_str!("../../../../tests/fixtures/registry/index.json");
        let index = accept_index(raw, 0).expect("the live index shape must parse");
        assert_eq!(index.plugins().len(), 3);
        let matters = index.find("matters").expect("matters is in the live index");
        assert!(matters.min_moss_version.is_some());
        assert!(matters.requires.is_none(), "matters declares no extra capability");
        assert!(matters.preview, "every live entry is preview today");
        let onionpress = index.find("onionpress").unwrap();
        assert!(onionpress.min_moss_version.is_none(), "an absent floor is legal");
        assert!(onionpress.requires_stack);
        // Named per binary since 2026-08-30. The blanket `execute_binary` this
        // used to pin no longer appears in the live index.
        assert_eq!(
            onionpress.requires.as_deref(),
            Some(
                [
                    "execute_binary:curl".to_string(),
                    "execute_binary:tar".to_string(),
                    "execute_binary:rm".to_string(),
                ]
                .as_slice()
            )
        );
    }

    #[test]
    fn parses_the_live_kill_list_shape_verbatim() {
        let raw = include_str!("../../../../tests/fixtures/registry/revoked.json");
        let list = accept_revoked(raw, 0, 0).expect("the live kill list shape must parse");
        assert!(list.revocations.is_empty(), "nothing is revoked today");
        assert_eq!(list.serial, 1);
    }
}
