//! UI string translations for supported languages
//!
//! All user-facing strings generated by moss are centralized here,
//! keyed by a string identifier and looked up by Language.

use super::Language;

/// Look up a translated UI string by key and language.
///
/// Returns the key itself if no translation is found.
/// The heading of a term namespace root (`authors`, `tags`) in `lang`: the
/// breadcrumb, the synthesized index and the editor's takeover folder all
/// name it from here.
pub fn term_root_title(lang: Language, ns: &str) -> &'static str {
    t(lang, if ns == moss_core::terms::AUTHOR_NS { "term_authors_title" } else { "term_tags_title" })
}

pub fn t(lang: Language, key: &str) -> &'static str {
    match key {
        // Month names (full)
        "month_1" => match lang {
            Language::En => "January",
            Language::ZhHans | Language::ZhHant => "1月",
        },
        "month_2" => match lang {
            Language::En => "February",
            Language::ZhHans | Language::ZhHant => "2月",
        },
        "month_3" => match lang {
            Language::En => "March",
            Language::ZhHans | Language::ZhHant => "3月",
        },
        "month_4" => match lang {
            Language::En => "April",
            Language::ZhHans | Language::ZhHant => "4月",
        },
        "month_5" => match lang {
            Language::En => "May",
            Language::ZhHans | Language::ZhHant => "5月",
        },
        "month_6" => match lang {
            Language::En => "June",
            Language::ZhHans | Language::ZhHant => "6月",
        },
        "month_7" => match lang {
            Language::En => "July",
            Language::ZhHans | Language::ZhHant => "7月",
        },
        "month_8" => match lang {
            Language::En => "August",
            Language::ZhHans | Language::ZhHant => "8月",
        },
        "month_9" => match lang {
            Language::En => "September",
            Language::ZhHans | Language::ZhHant => "9月",
        },
        "month_10" => match lang {
            Language::En => "October",
            Language::ZhHans | Language::ZhHant => "10月",
        },
        "month_11" => match lang {
            Language::En => "November",
            Language::ZhHans | Language::ZhHant => "11月",
        },
        "month_12" => match lang {
            Language::En => "December",
            Language::ZhHans | Language::ZhHant => "12月",
        },

        // Month names (abbreviated, for RSS)
        "month_abbr_1" => match lang {
            Language::En => "Jan",
            Language::ZhHans | Language::ZhHant => "1月",
        },
        "month_abbr_2" => match lang {
            Language::En => "Feb",
            Language::ZhHans | Language::ZhHant => "2月",
        },
        "month_abbr_3" => match lang {
            Language::En => "Mar",
            Language::ZhHans | Language::ZhHant => "3月",
        },
        "month_abbr_4" => match lang {
            Language::En => "Apr",
            Language::ZhHans | Language::ZhHant => "4月",
        },
        "month_abbr_5" => match lang {
            Language::En => "May",
            Language::ZhHans | Language::ZhHant => "5月",
        },
        "month_abbr_6" => match lang {
            Language::En => "Jun",
            Language::ZhHans | Language::ZhHant => "6月",
        },
        "month_abbr_7" => match lang {
            Language::En => "Jul",
            Language::ZhHans | Language::ZhHant => "7月",
        },
        "month_abbr_8" => match lang {
            Language::En => "Aug",
            Language::ZhHans | Language::ZhHant => "8月",
        },
        "month_abbr_9" => match lang {
            Language::En => "Sep",
            Language::ZhHans | Language::ZhHant => "9月",
        },
        "month_abbr_10" => match lang {
            Language::En => "Oct",
            Language::ZhHans | Language::ZhHant => "10月",
        },
        "month_abbr_11" => match lang {
            Language::En => "Nov",
            Language::ZhHans | Language::ZhHant => "11月",
        },
        "month_abbr_12" => match lang {
            Language::En => "Dec",
            Language::ZhHans | Language::ZhHant => "12月",
        },

        // Collection counter (plural)
        "article_counter" => match lang {
            Language::En => "articles",
            Language::ZhHans | Language::ZhHant => "篇",
        },

        // Collection counter (singular)
        "article_counter_singular" => match lang {
            Language::En => "article",
            Language::ZhHans | Language::ZhHant => "篇",
        },

        // Navigation
        "toggle_dark_mode" => match lang {
            Language::En => "Toggle dark mode",
            Language::ZhHans => "切换深色模式",
            Language::ZhHant => "切換深色模式",
        },
        "nav_toggle_menu" => match lang {
            Language::En => "Toggle menu",
            Language::ZhHans => "切换菜单",
            Language::ZhHant => "切換選單",
        },
        // Skip link (WCAG 2.4.1, moss#1047): the first focusable element on
        // every page, visually hidden until it receives keyboard focus, and
        // jumping straight to <main id="main-content"> — see shell.html and
        // `moss-skip-link` in site.css / components.rs.
        "skip_to_content" => match lang {
            Language::En => "Skip to content",
            Language::ZhHans => "跳到内容",
            Language::ZhHant => "跳到內容",
        },
        "nav_language" => match lang {
            Language::En => "Language",
            Language::ZhHans => "语言",
            Language::ZhHant => "語言",
        },
        "nav_search" => match lang {
            Language::En => "Search",
            Language::ZhHans => "搜索",
            Language::ZhHant => "搜尋",
        },
        // Where you are in a series. Two named placeholders, not the bare `{}`
        // used elsewhere, because both numbers appear in one sentence and the
        // caller replaces them one at a time.
        "series_position" => match lang {
            Language::En => "{n} of {total}",
            Language::ZhHans => "第 {n} 篇，共 {total} 篇",
            Language::ZhHant => "第 {n} 篇，共 {total} 篇",
        },
        // Floating nav island (ADR-049). All three name a control that has no
        // visible text of its own: the trail's landmark, the "…" that stands in
        // for the levels the trail had to drop, and the sections glyph.
        "nav_breadcrumb" => match lang {
            Language::En => "Breadcrumb",
            Language::ZhHans => "路径",
            Language::ZhHant => "路徑",
        },
        "nav_hidden_levels" => match lang {
            Language::En => "Show hidden levels",
            Language::ZhHans => "显示省略的层级",
            Language::ZhHant => "顯示省略的層級",
        },
        "nav_sections" => match lang {
            Language::En => "Sections on this page",
            Language::ZhHans => "本页章节",
            Language::ZhHant => "本頁章節",
        },
        // Search palette strings. Consumed by the site runtime, not by any Rust
        // emitter: generate-artifacts' `search-runtime` emitter lowers these
        // (plus `nav_search`) into frontend/site/search.generated.ts, so the
        // client and Rust never drift.
        "search_placeholder" => match lang {
            Language::En => "Search this site",
            Language::ZhHans => "搜索本站",
            Language::ZhHant => "搜尋本站",
        },
        "search_no_matches" => match lang {
            Language::En => "No matches for \"{query}\".",
            Language::ZhHans => "没有找到与“{query}”相关的内容。",
            Language::ZhHant => "沒有找到與「{query}」相關的內容。",
        },
        "search_results_label" => match lang {
            Language::En => "Search results",
            Language::ZhHans => "搜索结果",
            Language::ZhHant => "搜尋結果",
        },
        "nav_toggle_theme" => match lang {
            Language::En => "Toggle theme",
            Language::ZhHans => "切换主题",
            Language::ZhHant => "切換主題",
        },
        "reading_preferences" => match lang {
            Language::En => "Reading preferences",
            Language::ZhHans => "阅读偏好",
            Language::ZhHant => "閱讀偏好",
        },
        "text_small" => match lang {
            Language::En => "Small text",
            Language::ZhHans => "小号文字",
            Language::ZhHant => "小型文字",
        },
        "text_standard" => match lang {
            Language::En => "Standard text",
            Language::ZhHans => "标准文字",
            Language::ZhHant => "標準文字",
        },
        "text_large" => match lang {
            Language::En => "Large text",
            Language::ZhHans => "大号文字",
            Language::ZhHant => "大型文字",
        },
        "text_xlarge" => match lang {
            Language::En => "Extra large text",
            Language::ZhHans => "超大文字",
            Language::ZhHant => "特大文字",
        },
        "permalink_to" => match lang {
            Language::En => "Permalink to {}",
            Language::ZhHans => "固定链接：{}",
            Language::ZhHant => "永久連結：{}",
        },

        // Term namespace roots (generated /authors/ and /tags/ index pages)
        "term_authors_title" => match lang {
            Language::En => "Authors",
            Language::ZhHans => "作者",
            Language::ZhHant => "作者",
        },
        "term_tags_title" => match lang {
            Language::En => "Tags",
            Language::ZhHans => "标签",
            Language::ZhHant => "標籤",
        },

        // RSS / Subscribe
        "subscribe" => match lang {
            Language::En => "Subscribe",
            Language::ZhHans => "订阅",
            Language::ZhHant => "訂閱",
        },
        "rss" => "RSS",
        "subscribe_via_rss" => match lang {
            Language::En => "Subscribe via RSS",
            Language::ZhHans => "通过 RSS 订阅",
            Language::ZhHant => "透過 RSS 訂閱",
        },
        "follow_via" => match lang {
            Language::En => "Subscribe via",
            Language::ZhHans => "通过以下方式订阅",
            Language::ZhHant => "透過以下方式訂閱",
        },
        "enter_your_email" => match lang {
            Language::En => "Enter your email",
            Language::ZhHans => "输入你的邮箱",
            Language::ZhHant => "輸入你的電子郵件",
        },
        "sign_up" => match lang {
            Language::En => "Sign up",
            Language::ZhHans => "订阅",
            Language::ZhHant => "訂閱",
        },

        // Media pages
        "photography" => match lang {
            Language::En => "Photography",
            Language::ZhHans => "摄影",
            Language::ZhHant => "攝影",
        },
        "videos" => match lang {
            Language::En => "Videos",
            Language::ZhHans => "视频",
            Language::ZhHant => "影片",
        },
        "experiments" => match lang {
            Language::En => "Experiments",
            Language::ZhHans => "实验",
            Language::ZhHant => "實驗",
        },

        // Lightbox controls
        "close" => match lang {
            Language::En => "Close",
            Language::ZhHans => "关闭",
            Language::ZhHant => "關閉",
        },
        "previous" => match lang {
            Language::En => "Previous",
            Language::ZhHans => "上一个",
            Language::ZhHant => "上一個",
        },
        "next" => match lang {
            Language::En => "Next",
            Language::ZhHans => "下一个",
            Language::ZhHant => "下一個",
        },
        "view_in_article" => match lang {
            Language::En => "View in article",
            Language::ZhHans => "在文章中查看",
            Language::ZhHant => "在文章中查看",
        },

        // Comments
        // Empty-state section label. The call-to-action lives in the textarea
        // placeholder (`comment_placeholder`); the header is just a plain noun.
        "comment_count_zero" => match lang {
            Language::En => "Comments",
            Language::ZhHans => "评论",
            // zh-Hant: 留言 (comment), NOT 評論 (review/critique). Glossary SSOT.
            Language::ZhHant => "留言",
        },
        "comment_count_one" => match lang {
            Language::En => "1 comment",
            Language::ZhHans => "1条评论",
            Language::ZhHant => "1則留言",
        },
        // `{}` is replaced with the count at the call site
        // (comment::format_comment_count).
        "comment_count_many" => match lang {
            Language::En => "{} comments",
            Language::ZhHans => "{}条评论",
            Language::ZhHant => "{}則留言",
        },
        "comment_placeholder" => match lang {
            Language::En => "Leave your thoughts",
            Language::ZhHans | Language::ZhHant => "留下你的想法",
        },
        "comment_name" => match lang {
            Language::En => "Name",
            Language::ZhHans | Language::ZhHant => "名字",
        },
        "comment_email" => match lang {
            Language::En => "Email",
            Language::ZhHans => "邮箱",
            Language::ZhHant => "電子郵件",
        },
        "comment_website" => match lang {
            Language::En => "Website (optional)",
            Language::ZhHans => "网站（选填）",
            Language::ZhHant => "網站（選填）",
        },
        "comment_reply" => match lang {
            Language::En => "Reply",
            Language::ZhHans => "回复",
            Language::ZhHant => "回覆",
        },
        "anonymous" => match lang {
            Language::En => "Anonymous",
            Language::ZhHans | Language::ZhHant => "匿名",
        },
        // `{}` is replaced with the source display name (e.g. Matters, 豆瓣).
        "comment_reply_on" => match lang {
            Language::En => "Reply on {} ↗",
            Language::ZhHans => "去 {} 回复 ↗",
            Language::ZhHant => "去 {} 回覆 ↗",
        },

        // Defaults / fallbacks
        "untitled" => match lang {
            Language::En => "Untitled",
            Language::ZhHans => "无标题",
            Language::ZhHant => "無標題",
        },
        "untitled_site" => match lang {
            Language::En => "Untitled Site",
            Language::ZhHans => "无标题站点",
            Language::ZhHant => "無標題網站",
        },
        "site" => match lang {
            Language::En => "Site",
            Language::ZhHans => "站点",
            Language::ZhHant => "網站",
        },
        "collection" => match lang {
            Language::En => "Collection",
            Language::ZhHans => "合集",
            Language::ZhHant => "合集",
        },
        "unknown" => match lang {
            Language::En => "Unknown",
            Language::ZhHans => "未知",
            Language::ZhHant => "未知",
        },

        // Navigation / listing chrome
        "site_latest" => match lang {
            Language::En => "Latest",
            Language::ZhHans => "最新",
            Language::ZhHant => "最新",
        },
        "more_link" => match lang {
            Language::En => "More →",
            Language::ZhHans => "更多 →",
            Language::ZhHant => "更多 →",
        },

        // Embed error messages (use {} as placeholder, replaced at call site)
        "notebook_not_found" => match lang {
            Language::En => "Notebook not found: {}",
            Language::ZhHans => "找不到笔记本：{}",
            Language::ZhHant => "找不到筆記本：{}",
        },
        "table_not_found" => match lang {
            Language::En => "Table not found: {}",
            Language::ZhHans => "找不到表格：{}",
            Language::ZhHant => "找不到表格：{}",
        },
        // Not an error: the file exists, it just has not come down from the
        // cloud yet. The page publishes now and rebuilds when it arrives.
        "embed_downloading" => match lang {
            Language::En => "Downloading from the cloud: {}",
            Language::ZhHans => "正在从云端下载：{}",
            Language::ZhHant => "正在從雲端下載：{}",
        },

        // Colophon. Two strings for one link: `colophon_name` is what the
        // reader sees under the mark, `published_with_moss` is what a screen
        // reader announces. The visible half is deliberately just the name --
        // the mark above it already says "published with". WCAG 2.5.3 holds
        // because the announced name still contains the visible one.
        "colophon_name" => match lang {
            Language::En => "moss",
            Language::ZhHans => "青苔",
            Language::ZhHant => "青苔",
        },
        "published_with_moss" => match lang {
            Language::En => "Published with moss",
            Language::ZhHans => "青苔发布",
            Language::ZhHant => "青苔發佈",
        },

        // Service placeholders
        "available_after_publishing" => match lang {
            Language::En => "Available after publishing",
            Language::ZhHans => "发布后启用",
            Language::ZhHant => "發佈後啟用",
        },

        // Generated-site heading permalink anchor (aria-label emitted on
        // every slugged heading by moss-core's `render_heading`).
        "permalink_section" => match lang {
            Language::En => "Permalink to this section",
            Language::ZhHans => "本节固定链接",
            Language::ZhHant => "本節永久連結",
        },

        // Unrecognized key — return the key itself.
        // This uses a leaked string to satisfy the 'static lifetime.
        // Only happens for programmer errors (wrong key), not at runtime.
        other => {
            // For unknown keys, leak the string so we can return &'static str.
            // This is acceptable because unknown keys indicate a bug, not normal operation.
            Box::leak(other.to_string().into_boxed_str())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_published_with_moss_en() {
        assert_eq!(
            t(Language::En, "published_with_moss"),
            "Published with moss"
        );
    }

    #[test]
    fn test_published_with_moss_zh_hans() {
        assert_eq!(t(Language::ZhHans, "published_with_moss"), "青苔发布");
    }

    #[test]
    fn test_published_with_moss_zh_hant() {
        assert_eq!(t(Language::ZhHant, "published_with_moss"), "青苔發佈");
    }
}
