//! Link helpers — link resolution, candidate generation, and URL↔source mapping.
//!
//! These helpers back the `resolve_links`, `resolve_page_source`,
//! `resolve_url_for_file`, and `resolve_asset_url_for_file` Tauri commands in
//! `commands.rs`.

use crate::build::scan::article_map::ArticleMap;

// ── URL→source path helper ────────────────────────────────────────────────

/// Find the source path for a resolved internal URL, tolerating the
/// trailing-slash convention of `ArticleMap` keys.
///
/// Directory-style pages are stored under keys like `"research/"` (WITH
/// trailing slash). A naive `trim_matches('/')` strips that slash, causing
/// the lookup to miss every directory-style page and leaving `resolved_path`
/// as `None`, which breaks Cmd+Click navigation for the majority of real pages.
///
/// This helper tries both the bare key and the trailing-slash variant, so it
/// handles:
/// - `"research/"` (stored as-is)
/// - `"research"` (file-style, no trailing slash)
/// - `""` (home page, stored in `pages[""]`)
///
/// Fragment and query suffixes are stripped before the lookup.
pub fn source_path_for_url(map: &ArticleMap, url: &str) -> Option<String> {
    let bare = url
        .split(['#', '?'])
        .next()
        .unwrap_or(url)
        .trim_matches('/');
    let with_slash = format!("{bare}/");

    // Try the bare key first so that the home page (key `""`) is found
    // before `"/"` is tried; then fall through to the trailing-slash variant
    // which handles the common directory-style case.
    map.articles
        .get(bare)
        .map(|i| i.source_path.clone())
        .or_else(|| {
            map.articles
                .get(with_slash.as_str())
                .map(|i| i.source_path.clone())
        })
        .or_else(|| map.pages.get(bare).cloned())
        .or_else(|| map.pages.get(with_slash.as_str()).cloned())
}

// ── Public types ──────────────────────────────────────────────────────────

/// Result of resolving a preview URL to its source file and page type.
#[derive(Debug, Clone, serde::Serialize, specta::Type)]
pub struct PageSource {
    /// Absolute path to the source markdown file, if found.
    pub source_path: Option<String>,
    /// Whether this page is a directory listing (e.g., homepage, section index).
    pub is_dir: bool,
    /// Whether this URL corresponds to an article in the article map.
    pub is_article: bool,
    /// Syndication URLs from the article's frontmatter (empty if not an article).
    #[serde(default)]
    pub syndicated: Vec<String>,
    /// What an author would create to take over this page when moss generates
    /// it — a home note for an index-less folder or the root, a claim file
    /// for an unclaimed term, a translation for a language home. `None` for
    /// pages with a source and for generated output nothing can replace
    /// (feeds, redirect stubs). Computed by [`super::takeover::takeover_for`].
    #[serde(default)]
    pub takeover: Option<super::takeover::Takeover>,
    /// The editable source for this URL exists but could not be *identified*
    /// yet, because a file the resolve had to read is still coming down from
    /// the cloud.
    ///
    /// Distinct from `source_path: None`, which is a positive claim that this
    /// URL has nothing to edit. The two render different surfaces — a waiting
    /// pane that heals itself on arrival, versus "this page is generated by
    /// moss" — and conflating them is what told a user their home page did not
    /// exist while the provider was still handing it over.
    #[serde(default)]
    pub source_pending: bool,
}

/// Inner logic for `resolve_url_for_file`, extracted for testability.
///
/// `served_dir` is the directory the disk-fallback branches below must
/// consult — the CALLER's job to supply, not this function's to guess. Pass
/// the live preview server's actual served directory when one is running for
/// this folder; when none is (CLI, tests), pass
/// `MossPaths::initial_serve_dir()` as the best available fallback. This
/// function stays pure: it never asks a server for anything itself.
pub fn resolve_url_for_file_inner(
    rel_path: &str,
    folder_path: &std::path::Path,
    served_dir: &std::path::Path,
) -> Result<Option<String>, String> {
    use crate::build::scan::article_map::to_pretty_url;

    let moss_dir = folder_path.join(".moss");

    // Slot files (`footer.md`) have no page of their own. `build_article_map`
    // now excludes them, but this function also falls back to probing
    // `.moss/build.nosync/current/` on disk — and a generation built BEFORE that fix
    // still has a stale `footer/index.html` sitting there. Gate structurally so
    // the answer does not depend on which build produced the output tree.
    let slot_probe = moss_core::slug::normalize_separators(rel_path);
    if crate::build::footer::is_excluded_from_pages(slot_probe.trim_matches('/')) {
        return Ok(None);
    }

    // Load article map
    let map = ArticleMap::load(&moss_dir)?;

    // Generate candidate URL paths and look up each in the article map
    let candidates = source_to_url_candidates(rel_path);
    for candidate in &candidates {
        if map.articles.contains_key(candidate) {
            return Ok(Some(format!("/{}", candidate)));
        }
    }

    // Look up by source_path field. Handles slugified URLs where the source
    // filename differs from the URL key (e.g., Chinese filenames → English slugs).
    for article in map.articles.values() {
        if article.source_path == rel_path {
            return Ok(Some(format!("/{}", article.url_path)));
        }
    }

    // Section/folder index pages — the homepage, `posts/index.md`, and
    // self-named folder notes like `Research/Research.md` — live in the `pages`
    // map (url_path → source_path), NOT in `articles`. The `url_path` is already
    // in served form (slugified + lowercased dirs), so it matches the preview
    // server's URLs and the watcher's `changed_output_files`, which is what lets
    // SmartDiff refresh the preview after the folder index's frontmatter is
    // edited.
    //
    // Without this branch a self-named folder note resolves to None: the
    // `index.md` checks below don't match `Foo/Foo.md`, and the disk fallback
    // builds the wrong candidate `Foo/Foo/index.html`. The editor→preview
    // follower then never navigates, so the preview stays on whatever page it
    // was showing (typically the home page). This mirrors `resolve_page_source`,
    // which already consults `pages` for the reverse (url → source) direction.
    for (url_path, source_path) in &map.pages {
        if source_path == rel_path {
            return Ok(Some(format!("/{}", url_path)));
        }
    }

    // Fallback for index.md files when the `pages` lookup above didn't resolve
    // them — e.g. a legacy article map written before the `pages` field existed.
    // Modern builds record these in `pages`; this branch is defense-in-depth and
    // checks the compiled output on disk instead of trusting the map.
    //
    // Must consult `served_dir` — the directory the CALLER says the preview
    // server is actually serving right now — never a recomputed guess.
    // `MossPaths::initial_serve_dir()` (current if it exists, else staging) is
    // only correct before a vault's first seal; once `current` exists it stays
    // the answer forever, even while the live server has moved back to
    // `staging/` for a later rebuild (`SiteDirectoryState::switch_to`). A page
    // already written to staging — whether during a long first build, before
    // any generation is promoted, or by a later rebuild after one already was
    // — must resolve, or the editor never navigates the preview to a file
    // opened during that window. See df4ccb5d81, which fixed the pre-seal
    // half of this and left the post-seal half in place.
    if rel_path == "index.md" || rel_path == "index.markdown" {
        let site_file = served_dir.join("index.html");
        if site_file.exists() {
            return Ok(Some("/".to_string()));
        }
    }
    if let Some(dir) = rel_path
        .strip_suffix("/index.md")
        .or_else(|| rel_path.strip_suffix("/index.markdown"))
    {
        let site_file = served_dir.join(dir).join("index.html");
        if site_file.exists() {
            return Ok(Some(format!("/{}/", dir)));
        }
    }

    // Fallback: check if {served_dir}/{html_path} exists for non-article files
    // (e.g., standalone pages that aren't in the article map)

    // Try converting the source path to potential HTML output paths
    let stem = rel_path
        .trim_end_matches(".md")
        .trim_end_matches(".markdown");

    if stem != rel_path {
        // It's a markdown file — try pretty URL paths in served_dir
        let html_candidates = vec![
            format!("{}/index.html", stem),
            format!("{}.html", stem),
        ];

        for html_path in &html_candidates {
            let site_path = served_dir.join(html_path);
            if site_path.exists() {
                let pretty = to_pretty_url(html_path);
                return Ok(Some(format!("/{}", pretty)));
            }
        }
    }

    Ok(None)
}

/// Inner logic for `resolve_url_for_folder`, extracted for testability.
///
/// Maps a folder's project-relative source path (e.g. `My 1st Folder` or
/// `文字/书评`) to the site URL its index page is served at (e.g.
/// `/my-1st-folder/`). Every folder now gets an index page — including empty
/// ones — so this always resolves to `Some(url)` for a path inside the project.
///
/// The slug transform matches `compute_url_path`'s directory handling: each
/// directory segment goes through `generate_slug`, and `dir_overrides` (CJK
/// folder renames captured on the last build's `ArticleMap`) are honored. We
/// append `/index.html` before calling `resolve_path_with_overrides` so ALL of
/// the folder's own segments are treated as intermediate directories (the leaf
/// `index.html` is dropped by `to_pretty_url`), then render the pretty
/// trailing-slash form.
pub fn resolve_url_for_folder_inner(
    rel_path: &str,
    folder_path: &std::path::Path,
) -> Result<Option<String>, String> {
    use crate::build::scan::article_map::to_pretty_url;

    // Normalize separators and trim any leading/trailing slashes so both
    // `posts` and `posts/` (and Windows `posts\sub`) resolve identically.
    let normalized = moss_core::slug::normalize_separators(rel_path);
    let normalized = normalized.trim_matches('/');

    // The project root itself maps to the site root.
    if normalized.is_empty() {
        return Ok(Some("/".to_string()));
    }

    // Honor dir_overrides (CJK folder renames) captured on the last build. A
    // missing/unreadable map degrades to no overrides — the slug transform
    // still produces the correct URL for ASCII-named folders.
    let moss_dir = folder_path.join(".moss");
    let dir_overrides = ArticleMap::load(&moss_dir)
        .map(|m| m.dir_overrides)
        .unwrap_or_default();

    let mapped = moss_core::resolve::output_url::resolve_path_with_overrides(
        &format!("{}/index.html", normalized),
        &dir_overrides,
    );
    // `to_pretty_url("foo/bar/index.html")` -> `"foo/bar/"`; prepend the leading
    // slash to match the served folder-index URL.
    let pretty = to_pretty_url(&mapped);
    Ok(Some(format!("/{}", pretty)))
}

/// Build-INDEPENDENT resolve of a source file's EXPECTED served URL.
///
/// A pure slug transform mirroring [`resolve_url_for_folder_inner`]: it derives
/// the URL a file WILL be served at from its project-relative path + the last
/// build's `dir_overrides`, WITHOUT consulting the build output. Always resolves
/// to `Some(url)` for a real source path (even one not yet built), so the editor
/// can navigate the preview to a brand-new page IMMEDIATELY — exactly like every
/// folder already does via `resolve_url_for_folder`.
///
/// The build-DEPENDENT [`resolve_url_for_file_inner`] remains the accurate
/// post-build resolve; `PreviewFollower`'s FileChanged retry uses it to correct
/// the brief 404 window after a build lands.
///
/// Mechanism: strip the markdown extension, then treat the whole stem path like
/// a folder — append `/index.html` and run it through `resolve_path_with_overrides`
/// (which slugifies EVERY intermediate segment, including the file stem, and
/// honors CJK `dir_overrides`) + `to_pretty_url`. A home file (an index stem or a
/// self-named folder note) collapses to its containing folder's URL, mirroring the
/// build's home-page promotion, so `posts/index.md` → `/posts/` and
/// `Research/Research.md` → `/research/` rather than a nested `.../index/` path.
///
/// Returns `None` only for an empty/rootless path (not a real source file).
pub fn resolve_expected_url_for_file(
    rel_path: &str,
    folder_path: &std::path::Path,
) -> Option<String> {
    use crate::build::scan::article_map::to_pretty_url;

    // Normalize separators + trim slashes so `posts/hello.md` and the Windows
    // `posts\hello.md` resolve to the same URL.
    let normalized = moss_core::slug::normalize_separators(rel_path);
    let normalized = normalized.trim_matches('/');
    if normalized.is_empty() {
        return None; // not a real source file
    }

    // A slot file (`footer.md`) is layout chrome, not a page — it renders into
    // every page's `<footer>` and emits no output of its own. This resolver is
    // deliberately build-INDEPENDENT (it is what gives a brand-new file an
    // immediate preview URL before the first build), so it cannot learn the
    // exclusion from the article map the way `resolve_url_for_file_inner` does;
    // it has to consult the same structural predicate the build uses.
    if crate::build::footer::is_excluded_from_pages(normalized) {
        return None;
    }

    // Strip the markdown extension to get the extension-less stem path.
    let stem_path = normalized
        .strip_suffix(".md")
        .or_else(|| normalized.strip_suffix(".markdown"))
        .or_else(|| normalized.strip_suffix(".mdown"))
        .or_else(|| normalized.strip_suffix(".mkd"))
        .unwrap_or(normalized);

    // Split into (parent_dir, file_stem).
    let (parent_dir, file_stem) = match stem_path.rsplit_once('/') {
        Some((d, s)) => (d, s),
        None => ("", stem_path),
    };

    // A home file (index stem, lang-suffixed index, or self-named folder note)
    // is served AT its containing folder's URL — collapse it to the parent dir
    // so it doesn't gain a spurious nested `<folder>/<stem>/` path.
    let parent_name = parent_dir.rsplit('/').next().unwrap_or("");
    let dir_like: &str = if moss_core::home::is_home_file(file_stem, parent_name) {
        parent_dir
    } else {
        stem_path
    };

    // Honor the last build's dir_overrides (CJK folder renames); an
    // absent/unreadable map degrades to no overrides (ASCII folders still slug
    // correctly).
    let moss_dir = folder_path.join(".moss");
    let dir_overrides = ArticleMap::load(&moss_dir)
        .map(|m| m.dir_overrides)
        .unwrap_or_default();

    // Append `/index.html` so EVERY path segment (the file stem included) is
    // treated as an intermediate directory and slugified — same trick
    // `resolve_url_for_folder_inner` uses for a folder path.
    let with_index = if dir_like.is_empty() {
        "index.html".to_string()
    } else {
        format!("{}/index.html", dir_like)
    };
    let mapped = moss_core::resolve::output_url::resolve_path_with_overrides(
        &with_index,
        &dir_overrides,
    );
    let pretty = to_pretty_url(&mapped);
    Some(format!("/{}", pretty))
}

/// Generate candidate URL paths from a source file path.
///
/// Given a relative source file path (e.g., `"articles/post.md"`), returns
/// candidate URL paths that might exist as keys in the article map.
///
/// # Examples
/// - `"articles/post.md"` -> `["articles/post/", "articles/post"]`
/// - `"articles/post/index.md"` -> `["articles/post/"]`
/// - `"index.md"` -> `[""]`
pub fn source_to_url_candidates(source_path: &str) -> Vec<String> {
    let mut candidates = Vec::new();

    // Handle index.md files (directory-style)
    if source_path == "index.md" || source_path == "index.markdown" {
        // Root index -> root URL
        candidates.push(String::new());
        return candidates;
    }

    if let Some(dir) = source_path
        .strip_suffix("/index.md")
        .or_else(|| source_path.strip_suffix("/index.markdown"))
    {
        // "articles/post/index.md" -> "articles/post/"
        candidates.push(format!("{}/", dir));
        return candidates;
    }

    // Handle regular .md files
    if let Some(stem) = source_path
        .strip_suffix(".md")
        .or_else(|| source_path.strip_suffix(".markdown"))
    {
        // "articles/post.md" -> ["articles/post/", "articles/post"]
        // (directory-style pretty URL is more common, try first)
        candidates.push(format!("{}/", stem));
        candidates.push(stem.to_string());
    }

    candidates
}

/// Generate candidate source file paths from a URL path.
///
/// Fallback heuristic for pages not found in the article map.
/// The article map is the primary resolution path — this only runs
/// for pages compiled before the map included all pages.
pub fn url_to_source_candidates(url_path: &str) -> Vec<String> {
    let mut candidates = Vec::new();
    let clean = url_path
        .trim_end_matches('/')
        .trim_end_matches(".html")
        .trim_end_matches("/index");

    if !clean.is_empty() {
        // "posts/article" -> "posts/article.md"
        candidates.push(format!("{}.md", clean));
        // "posts/article" -> "posts/article/index.md"
        candidates.push(format!("{}/index.md", clean));
    } else {
        // Root -> "index.md"
        candidates.push("index.md".to_string());
    }

    candidates
}

// ── Asset URL resolver (extracted for testability) ────────────────────────────

/// Inner logic for `resolve_asset_url_for_file`, extracted for testability.
///
/// Maps a project-relative source asset path to the URL the preview server
/// serves it at. Returns `None` when the asset is absent from the current
/// build manifest (not yet built or excluded by scan rules).
///
/// Algorithm:
/// 1. Apply `resolve_path_with_overrides` with the ArticleMap's `dir_overrides`
///    to get the slugified output path.
/// 2. Prefer the `.webp` variant when present in `image_outputs`.
/// 3. Fall back to the original path if it appears in `files`, `image_outputs`,
///    or `video_outputs`.
pub fn resolve_asset_url_inner(
    rel_path: &str,
    hashes: &crate::types::content::SiteHashes,
    overrides: &std::collections::HashMap<String, String>,
) -> Option<String> {
    let output_path =
        moss_core::resolve::output_url::resolve_path_with_overrides(rel_path, overrides);

    // Prefer the WebP variant when present in image_outputs.
    let stem_no_ext = output_path
        .rsplit_once('.')
        .map_or(output_path.as_str(), |(stem, _)| stem);
    let webp_path = format!("{}.webp", stem_no_ext);

    if hashes.image_outputs.contains(&webp_path) {
        return Some(format!("/{}", webp_path));
    }

    // Fall back to the original output path.
    if hashes.files.contains_key(&output_path)
        || hashes.image_outputs.contains(&output_path)
        || hashes.video_outputs.contains(&output_path)
    {
        return Some(format!("/{}", output_path));
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::build::scan::article_map::ArticleMap;
    use crate::build::scan::article_map::ArticleInfo;
    use crate::moss_paths::MossPaths;
    use std::collections::HashMap;
    use std::fs;
    use tempfile::TempDir;

    /// Repo-local temp dir (test artifacts must live inside the repo —
    /// `target/test-tmp/` is gitignored).
    fn repo_temp() -> TempDir {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join("test-tmp");
        fs::create_dir_all(&dir).unwrap();
        TempDir::new_in(&dir).unwrap()
    }

    /// The `served_dir` argument for every test below that never reaches the
    /// disk-fallback branch (resolution happens via the `ArticleMap` first,
    /// or returns `None` before either matters): the no-live-server fallback
    /// a real caller would pass. Computed fresh each call so it sees whatever
    /// `current`/`staging` the test has created by the time it calls this.
    fn served(folder_path: &std::path::Path) -> std::path::PathBuf {
        MossPaths::from_moss_dir(folder_path.join(".moss")).initial_serve_dir()
    }

    /// Build an `ArticleInfo` fixture (fields not relevant to classification
    /// are zeroed — the type does not derive `Default`).
    fn make_article(source_path: &str, url_path: &str) -> ArticleInfo {
        ArticleInfo {
            source_path: source_path.into(),
            title: String::new(),
            content: String::new(),
            html_content: None,
            frontmatter: HashMap::new(),
            url_path: url_path.into(),
            date: None,
            tags: vec![],
            uid: None,
        }
    }

    // ── resolve_url_for_file_inner tests ──────────────────────────────────────

    /// Systematic-debugging verification for the "preview doesn't navigate to
    /// a brand-new page" bug report: a newly created file via the editor's
    /// `create_files` command is written completely empty (0 bytes, no
    /// frontmatter — see `editor::commands::create_files`). This test runs the
    /// REAL build pipeline (not a hand-constructed ArticleMap, unlike the
    /// other tests in this module) over a project containing exactly such a
    /// file, then asks `resolve_url_for_file_inner` — the same function the
    /// `resolveUrlForFile` Tauri command calls — whether the file resolves to
    /// a URL. If this fails, a 0-byte markdown file is being silently
    /// excluded from the article/page map and the preview-follower retry loop
    /// would spin forever waiting for a URL that will never arrive.
    #[test]
    fn newly_created_empty_markdown_file_resolves_after_build() {
        // NOTE: uses a `prefix("moss")` TempDir rather than the module's
        // `repo_temp()` helper. `repo_temp()` relies on `TempDir::new_in`'s
        // default `.tmp`-prefixed name, which is fine for the other tests in
        // this module (they hand-construct and save an `ArticleMap` directly,
        // never invoking the real directory scan). THIS test runs the real
        // `build_sync` pipeline, whose scanner excludes dot-prefixed
        // directories — including the scan ROOT itself (see
        // `build::scan::classify::is_excluded_dir_name` and
        // `tests/empty_folder_test.rs`'s `repo_local_temp` doc comment for the
        // same gotcha). A dot-prefixed root silently yields zero scanned
        // files, which would make this test pass/fail for the wrong reason.
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join("test-tmp");
        fs::create_dir_all(&base).unwrap();
        let project = tempfile::Builder::new()
            .prefix("moss")
            .tempdir_in(&base)
            .unwrap();
        let folder_path = project.path();

        // Existing home note, so the project isn't in the "zero markdown
        // files" synthetic-homepage branch (unrelated code path).
        fs::write(folder_path.join("index.md"), "# Home\n\nHome body.\n").unwrap();

        // Simulate `create_files` exactly: brand-new file, 0 bytes, no
        // frontmatter, at the project root (as the file tree would place it
        // absent a selected subfolder).
        let new_file_name = "Auguries of Innocence.md";
        fs::write(folder_path.join(new_file_name), "").unwrap();

        // One-shot, plugin-free pipeline run — what the app's `build_sync`
        // test helper does, spelled crate-side (the helper itself stays
        // app-side with the Tauri host ports).
        let rt = tokio::runtime::Runtime::new().unwrap();
        let result = rt.block_on(crate::build::run_pipeline(crate::build::PipelineConfig {
            root: crate::vault_root::VaultRoot::resolve(folder_path),
            progress: crate::build::stdout_sink(),
            plugins: crate::build::PluginMode::Skip,
            watch: false,
            start_server: false,
            host: crate::build::ports::host::test_host_ports(),
            trigger: crate::build::BuildTrigger::Full,
            exits_after_build: true,
            site_url_override: None,
            server_port: None,
            admission_epoch: None,
            live_port: None,
        }));
        assert!(result.is_ok(), "pipeline run failed: {:?}", result);

        let resolved =
            resolve_url_for_file_inner(new_file_name, folder_path, &served(folder_path)).unwrap();
        assert!(
            resolved.is_some(),
            "a content-less (0-byte) newly-created markdown file must still \
             resolve to a URL after a build completes — got None, meaning it \
             was excluded from the article/page map entirely"
        );
    }

    /// A self-named folder note (`Research/Research.md`, the index page for
    /// folder `Research`) must resolve to the folder's served URL, not None.
    ///
    /// These pages live in `ArticleMap.pages` (url_path → source_path), not in
    /// `.articles`. Before the `pages` lookup existed, the resolver returned
    /// None for them: the editor→preview follower then never navigated, and the
    /// preview stayed on the home page the user had just left.
    #[test]
    fn resolves_self_named_folder_note_to_folder_url() {
        let project = repo_temp();
        let folder_path = project.path();
        let moss_dir = folder_path.join(".moss");
        fs::create_dir_all(moss_dir.join("build.nosync")).unwrap();

        // The build records this folder index in `pages`, keyed by served
        // url_path (slugified + lowercased), NOT in `articles`.
        let mut map = ArticleMap::new();
        map.pages
            .insert("research/".to_string(), "Research/Research.md".to_string());
        map.save(&moss_dir).unwrap();

        let result = resolve_url_for_file_inner(
            "Research/Research.md",
            folder_path,
            &served(folder_path),
        )
        .unwrap();

        assert_eq!(result, Some("/research/".to_string()));
    }

    /// The root home file resolves to "/" via the `pages` map (key `""`),
    /// matching the build's `to_pretty_url("index.html") == ""`.
    #[test]
    fn resolves_root_home_file_to_slash() {
        let project = repo_temp();
        let folder_path = project.path();
        let moss_dir = folder_path.join(".moss");
        fs::create_dir_all(moss_dir.join("build.nosync")).unwrap();

        let mut map = ArticleMap::new();
        map.pages.insert(String::new(), "index.md".to_string());
        map.save(&moss_dir).unwrap();

        let result =
            resolve_url_for_file_inner("index.md", folder_path, &served(folder_path)).unwrap();

        assert_eq!(result, Some("/".to_string()));
    }

    /// A conventional `posts/index.md` section index resolves to "/posts/".
    /// Already worked via the disk fallback before the `pages` lookup existed;
    /// this pins that it still resolves (now through `pages`).
    #[test]
    fn resolves_conventional_section_index_to_folder_url() {
        let project = repo_temp();
        let folder_path = project.path();
        let moss_dir = folder_path.join(".moss");
        fs::create_dir_all(moss_dir.join("build.nosync")).unwrap();

        let mut map = ArticleMap::new();
        map.pages
            .insert("posts/".to_string(), "posts/index.md".to_string());
        map.save(&moss_dir).unwrap();

        let result = resolve_url_for_file_inner("posts/index.md", folder_path, &served(folder_path))
            .unwrap();

        assert_eq!(result, Some("/posts/".to_string()));
    }

    /// A file absent from both maps and from disk still resolves to None —
    /// the `pages` lookup must not widen resolution to unknown files.
    #[test]
    fn unknown_file_still_resolves_to_none() {
        let project = repo_temp();
        let folder_path = project.path();
        let moss_dir = folder_path.join(".moss");
        fs::create_dir_all(moss_dir.join("build.nosync")).unwrap();

        ArticleMap::new().save(&moss_dir).unwrap();

        let result = resolve_url_for_file_inner("ghost/Ghost.md", folder_path, &served(folder_path))
            .unwrap();

        assert_eq!(result, None);
    }

    /// A `draft: true` page in a CJK-named nested folder, with a CJK +
    /// full-width-punctuation filename, whose HTML has landed in `staging/`
    /// but the ArticleMap for this build hasn't been (re)saved yet. Two
    /// windows share this fallback, and the caller must consult the served
    /// dir it is actually told about — never a recomputed guess:
    ///
    /// - **Pre-seal** (`current` absent): the cold-start window on a large
    ///   vault's first build. No live server is up yet, so the caller passes
    ///   `MossPaths::initial_serve_dir()`, which degrades to `staging/`. Fixed
    ///   by df4ccb5d81.
    /// - **Post-seal** (`current` exists, a prior generation already
    ///   promoted): a later rebuild re-stages a newer page before the article
    ///   map resaves. The live server rests on `staging/` after every
    ///   completed rebuild (`SiteDirectoryState::switch_to`), so the caller
    ///   must pass THAT — passing `initial_serve_dir()` here instead answers
    ///   `current/`, which no longer has the page, and misses it. This is the
    ///   bug df4ccb5d81 left in place, and what threading `served_dir` from
    ///   the live server fixes.
    #[test]
    fn resolves_staged_draft_page_via_the_caller_supplied_served_dir() {
        let project = repo_temp();
        let folder_path = project.path();
        let moss_dir = folder_path.join(".moss");
        let paths = MossPaths::from_moss_dir(moss_dir.clone());

        // No article-map.json at all — ArticleMap::load() degrades to an
        // empty map, matching the pre-first-save window. The ArticleMap
        // lookup path must therefore miss and fall through to the disk
        // fallback below.

        // The page's HTML has already been written to staging/ — build
        // output lands there before the article map is (re)saved.
        let rel_path = "文字/信息网络/DWeb Camp，下次见.md";
        let staged_html = paths
            .staging_dir()
            .join("文字/信息网络/DWeb Camp，下次见/index.html");
        fs::create_dir_all(staged_html.parent().unwrap()).unwrap();
        fs::write(&staged_html, "").unwrap();

        // Pre-seal: no `current` pointer exists. A server-less caller's
        // fallback (`initial_serve_dir()`) degrades to `staging/` and finds it.
        assert_eq!(
            resolve_url_for_file_inner(rel_path, folder_path, &paths.initial_serve_dir())
                .unwrap(),
            Some("/文字/信息网络/DWeb Camp，下次见/".to_string()),
            "a page already staged before the first seal must resolve when \
             the caller passes the no-live-server fallback"
        );

        // Seal: promote a generation, so `current` now exists.
        fs::create_dir_all(paths.generation_dir("gen001")).unwrap();
        fs::create_dir_all(paths.generations_dir()).unwrap();
        paths.set_current_ptr("gen001").unwrap();

        // Post-seal, passing the LIVE server's actual served dir (staging,
        // where the live server rests after every completed rebuild): still
        // resolves.
        assert_eq!(
            resolve_url_for_file_inner(rel_path, folder_path, &paths.staging_dir()).unwrap(),
            Some("/文字/信息网络/DWeb Camp，下次见/".to_string()),
            "a page staged by a rebuild after the first seal must resolve \
             when the caller passes the live server's actual served dir"
        );

        // Post-seal, passing `initial_serve_dir()` instead (the old,
        // cold-start-only heuristic): `current` exists now, so it answers
        // `current/` and misses the page — the exact regression this test
        // guards against.
        assert_eq!(
            resolve_url_for_file_inner(rel_path, folder_path, &paths.initial_serve_dir())
                .unwrap(),
            None,
            "initial_serve_dir() is cold-start-only and must not stand in \
             for the live server's served dir once current exists"
        );
    }

    /// A slot file has no page, so the editor must resolve it to None and leave
    /// the preview where it is. This is the exact regression that produced the
    /// 404: `build_article_map` used to insert `footer.md` under `footer/`, and
    /// this resolver handed that key straight to the preview follower.
    #[test]
    fn slot_file_resolves_to_none() {
        let project = repo_temp();
        let folder_path = project.path();
        let moss_dir = folder_path.join(".moss");
        fs::create_dir_all(moss_dir.join("build.nosync")).unwrap();

        // A map that (wrongly) still carries the slot entry — e.g. written by a
        // pre-fix build — must not resurrect the URL.
        let mut map = ArticleMap::new();
        map.articles.insert(
            "footer/".to_string(),
            make_article("footer.md", "footer/"),
        );
        map.save(&moss_dir).unwrap();

        assert_eq!(
            resolve_url_for_file_inner("footer.md", folder_path, &served(folder_path)).unwrap(),
            None,
        );
        assert_eq!(
            resolve_url_for_file_inner("zh-hans/footer.md", folder_path, &served(folder_path))
                .unwrap(),
            None,
        );
    }

    /// The gate is filename-equality at a (language-)tree root, not a prefix
    /// match — a deeper `docs/footer.md` and a `footer-blog.md` are ordinary
    /// pages and must keep resolving.
    #[test]
    fn footer_lookalikes_are_not_slot_files() {
        let project = repo_temp();
        let folder_path = project.path();
        let moss_dir = folder_path.join(".moss");
        fs::create_dir_all(moss_dir.join("build.nosync")).unwrap();

        let mut map = ArticleMap::new();
        map.articles.insert(
            "docs/footer/".to_string(),
            make_article("docs/footer.md", "docs/footer/"),
        );
        map.articles.insert(
            "footer-blog/".to_string(),
            make_article("footer-blog.md", "footer-blog/"),
        );
        map.save(&moss_dir).unwrap();

        assert_eq!(
            resolve_url_for_file_inner("docs/footer.md", folder_path, &served(folder_path))
                .unwrap(),
            Some("/docs/footer/".to_string()),
        );
        assert_eq!(
            resolve_url_for_file_inner("footer-blog.md", folder_path, &served(folder_path))
                .unwrap(),
            Some("/footer-blog/".to_string()),
        );
    }

    // ── resolve_url_for_folder_inner tests ────────────────────────────────────

    /// Every folder now has an index page, so a plain (mixed-case, spaced)
    /// folder resolves to its slugified, trailing-slash URL — even with no
    /// `.moss` build present (the overrides map degrades to empty).
    #[test]
    fn folder_resolves_to_slugified_pretty_url() {
        let project = repo_temp();
        let folder_path = project.path();

        let result =
            resolve_url_for_folder_inner("My 1st Folder", folder_path).unwrap();

        assert_eq!(result, Some("/my-1st-folder/".to_string()));
    }

    /// A nested folder slugifies every segment and keeps the trailing slash.
    /// Trailing slashes / Windows separators on the input are tolerated.
    #[test]
    fn nested_folder_slugifies_every_segment() {
        let project = repo_temp();
        let folder_path = project.path();

        assert_eq!(
            resolve_url_for_folder_inner("Notes/Sub Dir/", folder_path).unwrap(),
            Some("/notes/sub-dir/".to_string()),
        );
        assert_eq!(
            resolve_url_for_folder_inner("Notes\\Sub Dir", folder_path).unwrap(),
            Some("/notes/sub-dir/".to_string()),
        );
    }

    /// The project root (empty relative path) maps to the site root "/".
    #[test]
    fn root_folder_resolves_to_slash() {
        let project = repo_temp();
        let folder_path = project.path();

        assert_eq!(
            resolve_url_for_folder_inner("", folder_path).unwrap(),
            Some("/".to_string()),
        );
    }

    /// A CJK folder rename recorded in the last build's `dir_overrides` is
    /// honored, so the folder URL matches the served (renamed) directory.
    #[test]
    fn folder_honors_dir_overrides() {
        let project = repo_temp();
        let folder_path = project.path();
        let moss_dir = folder_path.join(".moss");
        fs::create_dir_all(moss_dir.join("build.nosync")).unwrap();

        let mut map = ArticleMap::new();
        map.dir_overrides
            .insert("图片".to_string(), "image".to_string());
        map.save(&moss_dir).unwrap();

        assert_eq!(
            resolve_url_for_folder_inner("图片", folder_path).unwrap(),
            Some("/image/".to_string()),
        );
    }

    // ── resolve_expected_url_for_file tests ───────────────────────────────────

    /// A brand-new regular file (not yet built, no ArticleMap entry) still
    /// resolves — build-independently — to its expected slugified page URL, so
    /// the editor can navigate the preview immediately. Mixed case + spaces in
    /// the filename slug through exactly as the build would produce them.
    #[test]
    fn expected_url_for_not_yet_built_file_slugs_the_stem() {
        let project = repo_temp();
        let folder_path = project.path();

        assert_eq!(
            super::resolve_expected_url_for_file("Auguries of Innocence.md", folder_path),
            Some("/auguries-of-innocence/".to_string()),
        );
        assert_eq!(
            super::resolve_expected_url_for_file("posts/Hello World.md", folder_path),
            Some("/posts/hello-world/".to_string()),
        );
    }

    /// index.md at the root maps to `/`; a subfolder `index.md` and a self-named
    /// folder note both collapse to their containing folder's URL (home-page
    /// promotion), NOT a nested `.../index/` or `.../<name>/` path.
    #[test]
    fn expected_url_for_home_files_collapses_to_folder_url() {
        let project = repo_temp();
        let folder_path = project.path();

        assert_eq!(
            super::resolve_expected_url_for_file("index.md", folder_path),
            Some("/".to_string()),
        );
        assert_eq!(
            super::resolve_expected_url_for_file("posts/index.md", folder_path),
            Some("/posts/".to_string()),
        );
        assert_eq!(
            super::resolve_expected_url_for_file("Research/Research.md", folder_path),
            Some("/research/".to_string()),
        );
    }

    /// CJK folder renames recorded in the last build's `dir_overrides` are
    /// honored in the pure transform, matching the served (renamed) directory.
    #[test]
    fn expected_url_for_file_honors_dir_overrides() {
        let project = repo_temp();
        let folder_path = project.path();
        let moss_dir = folder_path.join(".moss");
        fs::create_dir_all(moss_dir.join("build.nosync")).unwrap();

        let mut map = ArticleMap::new();
        map.dir_overrides
            .insert("图片".to_string(), "image".to_string());
        map.save(&moss_dir).unwrap();

        assert_eq!(
            super::resolve_expected_url_for_file("图片/cat.md", folder_path),
            Some("/image/cat/".to_string()),
        );
    }

    /// The build-INDEPENDENT resolver is what gives a brand-new file an
    /// immediate preview URL, so it is the path a freshly-created `footer.md`
    /// takes. It must refuse slot files too, or creating one jumps the preview
    /// to a `/footer/` that will never exist.
    #[test]
    fn expected_url_for_slot_file_is_none() {
        let project = repo_temp();
        let folder_path = project.path();

        assert_eq!(
            super::resolve_expected_url_for_file("footer.md", folder_path),
            None,
        );
        assert_eq!(
            super::resolve_expected_url_for_file("zh-hans/footer.md", folder_path),
            None,
        );
        // Lookalikes are ordinary pages.
        assert_eq!(
            super::resolve_expected_url_for_file("docs/footer.md", folder_path),
            Some("/docs/footer/".to_string()),
        );
        assert_eq!(
            super::resolve_expected_url_for_file("footer-blog.md", folder_path),
            Some("/footer-blog/".to_string()),
        );
    }

    // ── source_path_for_url tests ─────────────────────────────────────────────

    /// Regression: directory-style article map keys include a trailing slash
    /// (e.g. `"research/"`).  `trim_matches('/')` stripped it, so the lookup
    /// always missed — resolved_path stayed None for every directory-style page
    /// and Cmd+Click navigation was broken for the majority of real pages.
    #[test]
    fn source_path_for_url_tolerates_trailing_slash_keys() {
        let mut map = ArticleMap::new();

        // directory-style article — key stored WITH trailing slash
        map.articles
            .insert("research/".into(), make_article("Research.md", "research/"));

        // folder index in pages map — key also has trailing slash
        map.pages
            .insert("news/".into(), "News/News.md".into());

        // home page — key is the empty string (to_pretty_url("index.html") == "")
        map.pages.insert(String::new(), "main.md".into());

        // directory-style article: URL arriving as "/research/" → "Research.md"
        assert_eq!(
            super::source_path_for_url(&map, "/research/"),
            Some("Research.md".into()),
            "directory-style article must resolve via trailing-slash key"
        );

        // same lookup without leading slash
        assert_eq!(
            super::source_path_for_url(&map, "research/"),
            Some("Research.md".into()),
        );

        // pages map entry: "/news/" → "News/News.md"
        assert_eq!(
            super::source_path_for_url(&map, "/news/"),
            Some("News/News.md".into()),
            "pages map entry must resolve via trailing-slash key"
        );

        // home page: "/" → "main.md" (bare key is "", which matches pages[""])
        assert_eq!(
            super::source_path_for_url(&map, "/"),
            Some("main.md".into()),
            "home page must resolve via empty key"
        );

        // completely unknown URL → None
        assert_eq!(
            super::source_path_for_url(&map, "/nope/"),
            None,
            "unknown URL must return None"
        );

        // Case-sensitive miss: lookup is hash-based; "/Research/" trims to
        // "Research", but the stored key is "research" — correct to return None
        // (a mismatch link isn't class=="resolved", so enrichment won't run).
        assert_eq!(
            super::source_path_for_url(&map, "/Research/"),
            None,
            "wrong-case URL must return None (case-sensitive HashMap)"
        );
    }

    /// Fragments and query strings are stripped before lookup.
    #[test]
    fn source_path_for_url_strips_fragment_and_query() {
        let mut map = ArticleMap::new();
        map.articles
            .insert("research/".into(), make_article("Research.md", "research/"));

        assert_eq!(
            super::source_path_for_url(&map, "/research/#heading"),
            Some("Research.md".into()),
            "fragment must be stripped before key lookup"
        );
        assert_eq!(
            super::source_path_for_url(&map, "/research/?q=foo"),
            Some("Research.md".into()),
            "query string must be stripped before key lookup"
        );
    }

    // ── resolve_asset_url_inner tests ─────────────────────────────────────────

    fn make_hashes() -> crate::types::content::SiteHashes {
        crate::types::content::SiteHashes::new()
    }

    /// An image with a WebP variant in image_outputs must resolve to the .webp URL.
    #[test]
    fn prefers_webp_variant_when_present_in_image_outputs() {
        let mut hashes = make_hashes();
        hashes.image_outputs.insert("assets/photo.webp".to_string());

        let result = super::resolve_asset_url_inner(
            "assets/photo.jpg",
            &hashes,
            &HashMap::new(),
        );

        assert_eq!(result, Some("/assets/photo.webp".to_string()));
    }

    /// An image without a WebP variant falls back to the original path in files.
    #[test]
    fn falls_back_to_original_when_no_webp_variant() {
        let mut hashes = make_hashes();
        hashes.files.insert(
            "assets/photo.jpg".to_string(),
            "100644:abc123".to_string(),
        );

        let result = super::resolve_asset_url_inner(
            "assets/photo.jpg",
            &hashes,
            &HashMap::new(),
        );

        assert_eq!(result, Some("/assets/photo.jpg".to_string()));
    }

    /// An asset absent from all manifest buckets resolves to None (not yet built).
    #[test]
    fn unbuilt_asset_resolves_to_none() {
        let hashes = make_hashes();

        let result = super::resolve_asset_url_inner(
            "assets/photo.jpg",
            &hashes,
            &HashMap::new(),
        );

        assert_eq!(result, None);
    }

    /// A video file present in video_outputs resolves to its output URL.
    #[test]
    fn video_in_video_outputs_resolves() {
        let mut hashes = make_hashes();
        hashes.video_outputs.insert("media/clip.mp4".to_string());

        let result = super::resolve_asset_url_inner(
            "media/clip.mp4",
            &hashes,
            &HashMap::new(),
        );

        assert_eq!(result, Some("/media/clip.mp4".to_string()));
    }

    /// Dir overrides slugify intermediate segments so a Chinese-named folder
    /// resolves to the slug-based output URL.
    #[test]
    fn dir_overrides_applied_to_slugify_intermediate_dirs() {
        let mut hashes = make_hashes();
        let out_path = "interactive/photo.webp";
        hashes.image_outputs.insert(out_path.to_string());

        let mut overrides = HashMap::new();
        overrides.insert("交互".to_string(), "interactive".to_string());

        let result = super::resolve_asset_url_inner(
            "交互/photo.jpg",
            &hashes,
            &overrides,
        );

        assert_eq!(result, Some(format!("/{}", out_path)));
    }
}
