// @generated by `cargo run --bin generate-artifacts --features dev-tools -- shortcode-catalog`
// — DO NOT EDIT. Source of truth: crates/moss-core/src/contract/shortcodes.rs
// (+ `ShortcodeKind` in crates/moss-core/src/ast/shortcode.rs).
// Structure only — labels, hints and translations are host overlays
// (design: docs/archive/2026-08-11-cm6-extraction-design.md §4).

export interface ShortcodeAttrInfo {
  readonly name: string;
  /** Present when this attr's VALUE names an asset file; editors scope asset search to these kinds. */
  readonly assetKinds?: readonly string[];
}

export interface ShortcodeInfo {
  /** Fence name: `:::name`. */
  readonly name: string;
  readonly attrs: readonly ShortcodeAttrInfo[];
  /** The opening-line attr that names this shortcode's asset (`hero` → `image`). */
  readonly assetAttr?: string;
  /** Canonical English insertion template, CM6 snippet syntax (`${n:placeholder}` tab stops). */
  readonly canonicalTemplate: string;
  /** False = parses and renders but is never offered to authors (e.g. `apply`). */
  readonly authorable: boolean;
}

export const SHORTCODES: readonly ShortcodeInfo[] = [
  {
    name: "subscribe",
    attrs: [
      { name: "button" },
      { name: "placeholder" },
    ],
    canonicalTemplate: "subscribe {button=\"${1:Subscribe}\"}\n:::",
    authorable: true,
  },
  {
    name: "buttons",
    attrs: [],
    canonicalTemplate: "buttons\n[${1:Get started}](${2:/})\n:::",
    authorable: true,
  },
  {
    name: "gallery",
    attrs: [
      { name: "cols" },
    ],
    canonicalTemplate: "gallery {cols=${1:3}}\n![](${2:photo.jpg})\n:::",
    authorable: true,
  },
  {
    name: "hero",
    attrs: [
      { name: "image", assetKinds: ["Image", "Video"] },
      { name: "wide" },
    ],
    assetAttr: "image",
    canonicalTemplate: "hero {image=${1:photo.jpg}}\n# ${2:Title}\n${3:Subtitle}\n:::",
    authorable: true,
  },
  {
    name: "grid",
    attrs: [
      { name: "cols" },
      { name: "wide" },
    ],
    canonicalTemplate: "grid {cols=${1:2}}\n${2:cell one}\n+++\n${3:cell two}\n:::",
    authorable: true,
  },
  {
    name: "recent",
    attrs: [
      { name: "count" },
      { name: "since" },
      { name: "last" },
    ],
    canonicalTemplate: "recent {count=${1:5}}\n${2:No posts yet.}\n:::",
    authorable: true,
  },
  {
    name: "apply",
    attrs: [
      { name: "placeholder" },
      { name: "button" },
    ],
    canonicalTemplate: "apply {button=\"${1:Apply}\"}\n:::",
    authorable: false,
  },
];
