/**
 * A bare inline video (`![[clip.mp4]]` on its own line, not wrapped in a
 * `<figure>`) takes its own decoded shape, not a box forced to 16:9. moss
 * emits it as a direct `<video>` child of `<article>` — `article video`,
 * the second branch of site.css's selector below, not the `article p >
 * video` first branch, which covers an embed pulldown-cmark keeps inside a
 * paragraph (e.g. alongside other inline content).
 *
 * `article p > video, article video` used to set `aspect-ratio: 16 / 9`
 * unconditionally, with `object-fit: contain`. A viewer's own 1280x1080 clip
 * (DAR 32:27) rendered at ~65% of the column's width — exactly
 * (32/27)/(16/9) — with `--moss-color-surface` bars on both sides. Only a
 * real engine that has decoded the video's `loadedmetadata` knows its natural
 * ratio, so a golden-string HTML test cannot see this: the emitted markup is
 * identical whether the box below it is shaped right or wrong.
 *
 * Site: tests/e2e/helpers/gate-sites.ts → videoEmbedShapeGate(), whose
 * `clip.mp4` is a synthetic 640x540 (DAR 32:27, not 16:9) fixture generated by
 * `syntheticTestClip` — small enough to decode fast, shaped enough to
 * pillarbox visibly under the old rule, and long enough for moss's own
 * thumbnail generator to produce a real poster (see that function's doc
 * comment — a too-short clip breaks the poster, which breaks Chromium's
 * aspect-ratio resolution too, in a way that looks like an engine gap and
 * isn't one).
 */
import { test, expect } from "@playwright/test";

test.describe("video embed shape", () => {
  test("the box matches the video's own decoded ratio, and fills the column", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 900 });
    await page.goto("/");

    const video = page.locator("article video").first();
    await expect(video).toBeVisible();

    // `preload="metadata"` fetches just enough for the browser to know the
    // real decoded size; wait for that rather than assuming it already
    // happened by the time boundingBox is read.
    await video.evaluate(
      (el) =>
        new Promise<void>((resolve) => {
          const v = el as HTMLVideoElement;
          if (v.readyState >= 1) return resolve();
          v.addEventListener("loadedmetadata", () => resolve(), { once: true });
        }),
    );

    const dims = await video.evaluate((el) => {
      const v = el as HTMLVideoElement;
      return { width: v.videoWidth, height: v.videoHeight };
    });
    // Sanity check on the fixture itself — if this fails, the rest of the
    // test proves nothing about the CSS.
    expect(dims.width, "fixture must have decoded real dimensions").toBeGreaterThan(0);
    expect(dims.width / dims.height).toBeCloseTo(640 / 540, 2);

    const box = (await video.boundingBox())!;
    expect(
      box.width / box.height,
      "the <video> box must match the video's own ratio, not a forced 16:9",
    ).toBeCloseTo(dims.width / dims.height, 1);

    // The content-box width, not the border-box `getBoundingClientRect()`
    // width — `article.container` carries its own inline padding, which the
    // video (100% of its content box) is not meant to include.
    const column = await page.locator("article.container").evaluate((el) => {
      const r = el.getBoundingClientRect();
      const s = getComputedStyle(el);
      return r.width - parseFloat(s.paddingLeft) - parseFloat(s.paddingRight);
    });
    expect(
      Math.abs(box.width - column),
      "no pillarbox: the video element itself should fill the content column",
    ).toBeLessThanOrEqual(2);
  });
});
