/**
 * fullscreen.ts - Unified fullscreen for media content
 *
 * Replaces lightbox.ts. Same black-background container for all media types:
 * - Gallery images: prev/next arrows, keyboard navigation
 * - Video: native controls
 * - Interactive iframes: exit button
 *
 * Uses the same #lightbox HTML structure generated by media_collection.rs.
 * Opens from media-collection grid items (`.media-item`) and from the images
 * of a `:::gallery` (`.moss-gallery-link`); the arrows step through the items
 * of the group that was opened — all media items, or that one gallery.
 */

// Make this a module to allow declare global
export {};

interface MediaItem {
  type: "image" | "video" | "interactive";
  src: string;
  title: string;
  articleUrl: string;
}

(function () {
  const lightbox = document.getElementById("lightbox");
  if (!lightbox) return;

  const content = lightbox.querySelector(".lightbox-content");
  const image = lightbox.querySelector(".lightbox-image") as HTMLImageElement | null;
  const video = lightbox.querySelector(".lightbox-video") as HTMLVideoElement | null;
  const iframe = lightbox.querySelector(".lightbox-iframe") as HTMLIFrameElement | null;
  const titleEl = lightbox.querySelector(".lightbox-title") as HTMLElement | null;
  const articleLink = lightbox.querySelector(".lightbox-article-link") as HTMLAnchorElement | null;

  let items: MediaItem[] = [];
  let currentIndex = 0;
  let triggers: HTMLElement[] = [];

  // One group per gallery; every media-collection item shares the page group.
  const groups = new Map<Element | Document, { items: MediaItem[]; triggers: HTMLElement[] }>();
  document
    .querySelectorAll<HTMLElement>(".media-item, .moss-gallery-link")
    .forEach((trigger) => {
      const key = trigger.closest(".moss-gallery") ?? document;
      const group = groups.get(key) ?? { items: [], triggers: [] };
      groups.set(key, group);
      const index = group.items.length;
      group.triggers.push(trigger);
      group.items.push({
        type: (trigger.dataset.type as MediaItem["type"]) || "image",
        src: trigger.dataset.src || (trigger as HTMLAnchorElement).href || "",
        title: trigger.dataset.title || "",
        articleUrl: trigger.dataset.article || "",
      });

      trigger.addEventListener("click", (e: MouseEvent) => {
        e.preventDefault();
        open(group, index);
      });
      trigger.addEventListener("keydown", (e: KeyboardEvent) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          open(group, index);
        }
      });
    });

  function open(group: { items: MediaItem[]; triggers: HTMLElement[] }, index: number): void {
    items = group.items;
    currentIndex = index;
    triggers = group.triggers;
    show(items[index]);
    lightbox.hidden = false;
    lightbox.focus();
    document.body.style.overflow = "hidden";
  }

  function close(): void {
    lightbox.hidden = true;
    document.body.style.overflow = "";
    if (video) video.pause();
    if (iframe) iframe.src = "";
    // Return focus to the thumbnail the viewer was opened from — or, if the
    // reader stepped to another image, to that one.
    triggers[currentIndex]?.focus();
  }

  function show(item: MediaItem): void {
    // Hide all media elements
    if (image) image.hidden = true;
    if (video) {
      video.hidden = true;
      video.pause();
    }
    if (iframe) {
      iframe.hidden = true;
      iframe.src = "";
    }

    switch (item.type) {
      case "video":
        if (video) {
          video.src = item.src;
          video.hidden = false;
        }
        break;
      case "interactive":
        if (iframe) {
          iframe.src = item.src;
          iframe.hidden = false;
        }
        break;
      default:
        if (image) {
          image.src = item.src;
          image.alt = item.title;
          image.hidden = false;
        }
    }

    if (titleEl) titleEl.textContent = item.title;
    if (articleLink) {
      articleLink.href = item.articleUrl;
      articleLink.hidden = !item.articleUrl;
    }
  }

  function next(): void {
    if (items.length === 0) return;
    currentIndex = (currentIndex + 1) % items.length;
    show(items[currentIndex]);
  }

  function prev(): void {
    if (items.length === 0) return;
    currentIndex = (currentIndex - 1 + items.length) % items.length;
    show(items[currentIndex]);
  }

  // Event listeners
  lightbox.querySelector(".lightbox-close")?.addEventListener("click", close);
  lightbox.querySelector(".lightbox-next")?.addEventListener("click", next);
  lightbox.querySelector(".lightbox-prev")?.addEventListener("click", prev);

  lightbox.addEventListener("click", (e: MouseEvent) => {
    if (e.target === lightbox || e.target === content) close();
  });

  document.addEventListener("keydown", (e: KeyboardEvent) => {
    if (lightbox.hidden) return;
    switch (e.key) {
      case "Escape":
        close();
        break;
      case "ArrowRight":
        next();
        break;
      case "ArrowLeft":
        prev();
        break;
    }
  });

  // Touch swipe support
  let touchStartX = 0;
  lightbox.addEventListener(
    "touchstart",
    (e: TouchEvent) => {
      touchStartX = e.touches[0].clientX;
    },
    { passive: true }
  );

  lightbox.addEventListener(
    "touchend",
    (e: TouchEvent) => {
      const diff = e.changedTouches[0].clientX - touchStartX;
      if (Math.abs(diff) > 50) {
        diff > 0 ? prev() : next();
      }
    },
    { passive: true }
  );
})();
