// @generated by `cargo run --bin generate-artifacts --features dev-tools -- search-runtime`
// — DO NOT EDIT. Sources: the desktop app's served-path module (search_mount_url)
// and its i18n strings module (nav_search, search_*).

/** Pagefind bundle mount, and the palette's pinned Pagefind `baseUrl` denominator. */
export const BUNDLE_PATH = "/_moss/pagefind/";

export interface SearchStrings {
  label: string;
  placeholder: string;
  empty: string;
  resultsLabel: string;
}

export const STRINGS: Record<"en" | "zh-hans" | "zh-hant", SearchStrings> = {
  "en": {
    label: "Search",
    placeholder: "Search this site",
    empty: "No matches for \"{query}\".",
    resultsLabel: "Search results",
  },
  "zh-hans": {
    label: "搜索",
    placeholder: "搜索本站",
    empty: "没有找到与“{query}”相关的内容。",
    resultsLabel: "搜索结果",
  },
  "zh-hant": {
    label: "搜尋",
    placeholder: "搜尋本站",
    empty: "沒有找到與「{query}」相關的內容。",
    resultsLabel: "搜尋結果",
  },
};
